spring.application.name=STUDENT-SERVICE
# Eureka Config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#eureka.client.service-url.defaultZone=http://serviceregistry:8761/eureka/

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=30
server.port=8081
# JWT Secret
#jwt.secret=qwerStyuoSecretKeyThatghLongEnoug4343!

# Actuator (for Spring Boot Admin)
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.defaults.enabled=true

# Spring Boot Admin Client
spring.boot.admin.client.url=http://localhost:9091
#spring.boot.admin.client.instance.service-base-url=http://localhost:8088

# Database Config
spring.datasource.url=jdbc:postgresql://localhost:5432/IDCARD_Generator-Student
spring.datasource.username=postgres
spring.datasource.password=post#4343
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
eureka.instance.health-check-url-path=/actuator/health
eureka.instance.status-page-url-path=/actuator/info
eureka.client.healthcheck.enabled=true
